#!/bin/bash

SBDIR=$(pwd)
SBPKGDIR="$SBDIR/+packages-svn-$(date +%F)"
SBLOG="$SBDIR/build-svn-$(date +%F).log"
set -o pipefail

build_svn()
{
	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
	cd "$1" || return 1 
	"./$1-svn.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
	cd "$SBDIR" || return 1
	if [[ $ARCH ]]; then
		upgradepkg --install-new --reinstall "$1/$1-*-$ARCH-*.t[gx]z" | tee -a "$SBLOG" || return 1
		mv $1/$1-*-$ARCH-*.t[gx]z "$SBPKGDIR" || return 1
	else
		upgradepkg --install-new --reinstall "$1/$1-*-*-*.t[gx]z" | tee -a "$SBLOG" || return 1
		mv $1/$1-*-*-*.t[gx]z "$SBPKGDIR" || return 1
	fi
}

prompt_exit()
{
	local res
	read -p "Retry, skip, exit? [r,S,e] " SBANS
	if [[ "$SBANS" == [eE] ]]; then
		exit 1
	elif [[ "$SBANS" == [rR] ]]; then
		res=0
	else
		echo -e "\n*** Skip building $1 ***\n" | tee -a "$SBLOG"
		res=1
	fi
	cd "$SBDIR" || return 1
	return $res
}

try_build_svn()
{
	while true; do
		build_svn "$@"
		if [[ $? == 0 ]]; then
			break
		else
			prompt_exit "$1" || break
		fi
	done
}

echo "[ E17 BUILD START $(date +%T) ]" | tee -a "$SBLOG" || exit 1
mkdir -p "$SBPKGDIR"

# EFL
try_build_svn  eina
try_build_svn  eet
try_build_svn  evas
try_build_svn  evas_generic_loaders
try_build_svn  ecore
try_build_svn  embryo
try_build_svn  edje
try_build_svn  e_dbus
try_build_svn  efreet
try_build_svn  eeze

# Misc. libs and apps
try_build_svn  eio
# PROTO/
try_build_svn  azy
try_build_svn  epdf
# try_build_svn  eyesight
try_build_svn  libeweather
try_build_svn  emap
try_build_svn  esskyuehl
try_build_svn  eupnp
try_build_svn  emotion
try_build_svn  emprint
try_build_svn  ethumb
try_build_svn  elementary
try_build_svn  ekbd
try_build_svn  elsa
try_build_svn  ecrire
try_build_svn  ephoto
try_build_svn  envision
try_build_svn  exalt
try_build_svn  enjoy
try_build_svn  equate

# Enlightenment
try_build_svn  enlightenment
try_build_svn  e_modules-comp-scale
try_build_svn  e_modules-screenshot
try_build_svn  e_modules-taskbar
try_build_svn  e_modules-e-tiling
try_build_svn  e_modules-engage
try_build_svn  e_modules-exalt-client
try_build_svn  e_modules-eweather
# try_build_svn  e_modules-eenvader.fractal
# try_build_svn  e_modules-mpdule
# try_build_svn  e_modules-calendar
# try_build_svn  e_modules-weather
# wlan

# Themes
cd themes
. themes-svn.build
cd -

# Update dependencies graph
cd "$SBDIR"
./depgraph
