#!/bin/bash

SBDIR=$(pwd)
SBPKGDIR="$SBDIR/+packages-stable-$(date +%F)"
SBLOG="$SBDIR/build-stable-$(date +%F).log"
set -o pipefail

build_package()
{
	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
	cd "$1" || return 1
	"./$1.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
	cd "$SBDIR" || return 1
	if [[ $ARCH ]]; then
		upgradepkg --install-new --reinstall "$1/$1-*-$ARCH-*.t[gx]z" | tee -a "$SBLOG" || return 1
		mv $1/$1-*-$ARCH-*.t[gx]z "$SBPKGDIR" || return 1
	else
		upgradepkg --install-new --reinstall "$1/$1-*-*-*.t[gx]z" | tee -a "$SBLOG" || return 1
		mv $1/$1-*-*-*.t[gx]z "$SBPKGDIR" || return 1
	fi
}

prompt_exit()
{
	local res
	read -p "Retry, skip, exit? [r,S,e] " SBANS
	if [[ "$SBANS" == [eE] ]]; then
		exit 1
	elif [[ "$SBANS" == [rR] ]]; then
		res=0
	else
		echo -e "\n*** Skip building $1 ***\n" | tee -a "$SBLOG"
		res=1
	fi
	cd "$SBDIR" || return 1
	return $res
}

try_build_pkg()
{
	while true; do
		build_package "$@"
		if [[ $? == 0 ]]; then
			break
		else
			prompt_exit "$1" || break
		fi
	done
}

echo "[ E17 BUILD START $(date +%T) ]" | tee -a "$SBLOG" || exit 1
mkdir -p "$SBPKGDIR"

# EFL
try_build_pkg  eina
try_build_pkg  eet
try_build_pkg  evas
try_build_pkg  evas_generic_loaders
try_build_pkg  ecore
try_build_pkg  embryo
try_build_pkg  eio
try_build_pkg  edje
try_build_pkg  efreet
try_build_pkg  e_dbus
try_build_pkg  eeze
try_build_pkg  emotion
try_build_pkg  ethumb
try_build_pkg  elementary

# Apps
try_build_pkg  expedite
try_build_pkg  terminology
# try_build_pkg  eperiodique

# Games
# try_build_pkg  elemines

# Enlightenment
try_build_pkg  enlightenment
