#!/bin/bash

SBDIR=$(pwd)
SBPKGDIR="$SBDIR/+packages-e18-$(date +%F)"
SBLOG="$SBDIR/build-e18-$(date +%F).log"
set -o pipefail

build_package()
{
	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
	cd "$1" || return 1
	"./$1.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
	cd "$SBDIR" || return 1
	if [[ $ARCH ]]; then
		upgradepkg --install-new --reinstall $1/$1-*-$ARCH-*.txz | tee -a "$SBLOG" || return 1
		mv $1/$1-*-$ARCH-*.txz "$SBPKGDIR" || return 1
	else
		upgradepkg --install-new --reinstall $1/$1-*-*-*.txz | tee -a "$SBLOG" || return 1
		mv $1/$1-*-*-*.txz "$SBPKGDIR" || return 1
	fi
}

prompt_exit()
{
	local res
	read -p "Retry, skip, exit? [r,S,e] " SBANS
	if [[ "$SBANS" == [eE] ]]; then
		exit 1
	elif [[ "$SBANS" == [rR] ]]; then
		res=0
	else
		echo -e "\n*** Skip building $1 ***\n" | tee -a "$SBLOG"
		res=1
	fi
	cd "$SBDIR" || return 1
	return $res
}

try_build_pkg()
{
	while true; do
		build_package "$@"
		if [[ $? == 0 ]]; then
			break
		else
			prompt_exit "$1" || break
		fi
	done
}

echo "[ E18 BUILD START $(date +%T) ]" | tee -a "$SBLOG" || exit 1
mkdir -p "$SBPKGDIR"

# EFL
try_build_pkg  efl
try_build_pkg  evas_generic_loaders
try_build_pkg  webkit-efl
try_build_pkg  elementary

# Apps
try_build_pkg  terminology
try_build_pkg  eperiodique

# Developer tools
try_build_pkg  expedite

# Games
try_build_pkg  etrophy
try_build_pkg  elemines

# Enlightenment
try_build_pkg  enlightenment

# Update dependencies graph
cd "$SBDIR"
./depgraph > e18-depgraph.dot
