#!/bin/bash

SBDIR=$(pwd)
SBPKGDIR="$SBDIR/+packages-svn-$(date +%F)"
SBTHMDIR="$SBDIR/+themes-svn-$(date +%F)"
SBLOG="$SBDIR/build-svn-$(date +%F).log"
set -o pipefail

build_package_svn()
{
	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
	cd "$1" || return 1
	"./$1-svn.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
	cd "$SBDIR" || return 1
	if [[ $ARCH ]]; then
		upgradepkg --install-new --reinstall "$1/$1-*-$ARCH-*.t[gx]z" | tee -a "$SBLOG" || return 1
		mv $1/$1-*-$ARCH-*.t[gx]z "$SBPKGDIR" || return 1
	else
		upgradepkg --install-new --reinstall "$1/$1-*-*-*.t[gx]z" | tee -a "$SBLOG" || return 1
		mv $1/$1-*-*-*.t[gx]z "$SBPKGDIR" || return 1
	fi
}

build_theme_svn()
{
	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
	cd themes || return 1
	"./$1-svn.build" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
	mv *.edj "$SBTHMDIR" || return 1
	cd "$SBDIR" || return 1
}

prompt_exit()
{
	local res
	read -p "Retry, skip, exit? [r,S,e] " SBANS
	if [[ "$SBANS" == [eE] ]]; then
		exit 1
	elif [[ "$SBANS" == [rR] ]]; then
		res=0
	else
		echo -e "\n*** Skip building $1 ***\n" | tee -a "$SBLOG"
		res=1
	fi
	cd "$SBDIR" || return 1
	return $res
}

try_build_pkg_svn()
{
	while true; do
		build_package_svn "$@"
		if [[ $? == 0 ]]; then
			break
		else
			prompt_exit "$1" || break
		fi
	done
}

try_build_thm_svn()
{
	# ignore errors as themes are not really important
	local res
	build_theme_svn "$@" || cd "$SBDIR"
}

echo "[ E17 BUILD START $(date +%T) ]" | tee -a "$SBLOG" || exit 1
mkdir -p "$SBPKGDIR"
mkdir -p "$SBTHMDIR"

# EFL
try_build_pkg_svn  eina
try_build_pkg_svn  eet
try_build_pkg_svn  evas
try_build_pkg_svn  evas_generic_loaders
try_build_pkg_svn  ecore
try_build_pkg_svn  embryo
try_build_pkg_svn  eio
try_build_pkg_svn  edje
try_build_pkg_svn  efreet
try_build_pkg_svn  e_dbus
try_build_pkg_svn  eeze
try_build_pkg_svn  emotion

# Misc. libs
try_build_pkg_svn  azy
try_build_pkg_svn  epdf
# try_build_pkg_svn  eyesight
try_build_pkg_svn  libeweather
try_build_pkg_svn  emap
try_build_pkg_svn  esskyuehl
try_build_pkg_svn  eupnp
try_build_pkg_svn  emprint
try_build_pkg_svn  ethumb
try_build_pkg_svn  ephysics
try_build_pkg_svn  elementary

# Apps
try_build_pkg_svn  ekbd
try_build_pkg_svn  entrance
try_build_pkg_svn  ecrire
try_build_pkg_svn  ephoto
try_build_pkg_svn  envision
try_build_pkg_svn  exalt
try_build_pkg_svn  enjoy
try_build_pkg_svn  equate
try_build_pkg_svn  terminology

# Enlightenment
try_build_pkg_svn  enlightenment
try_build_pkg_svn  e_modules-comp-scale
try_build_pkg_svn  e_modules-net
try_build_pkg_svn  e_modules-news
try_build_pkg_svn  e_modules-places
try_build_pkg_svn  e_modules-screenshot
try_build_pkg_svn  e_modules-taskbar
try_build_pkg_svn  e_modules-engage
try_build_pkg_svn  e_modules-exalt-client
try_build_pkg_svn  e_modules-eweather
try_build_pkg_svn  e_modules-eenvader.fractal
# try_build_pkg_svn  e_modules-photo
# try_build_pkg_svn  e_modules-mpdule
# try_build_pkg_svn  e_modules-calendar
# try_build_pkg_svn  e_modules-weather
# wlan

# Themes
try_build_thm_svn  23oz
try_build_thm_svn  darkness
try_build_thm_svn  detourious
try_build_thm_svn  efenniht

# Update dependencies graph
cd "$SBDIR"
./depgraph
